baseURL = 'https://ryanpenn.github.io/notebook'
languageCode = 'en-us'
title = 'Notebook'
theme = "hyde"

[author]
    name = "ryan"
    homepage = "https://ryanpenn.github.io/notebook"

[Menus]
  main = [
      {Name = "Posts", URL = "/posts/", Weight = 1},
      {Name = "Tags", URL = "/tags/", Weight = 5},
      {Name = "Github", URL = "https://github.com/ryanpenn/", Weight = 10},
    ]

[params]
  description = "My notes on development and other things."
  # 08 09 0a 0b 0c 0d 0e 0f
  themeColor = "theme-base-0d"
